// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show Firebase, FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
//await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
//);
Future<void> initializeApp() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}
 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLqLkXpZwDglQTmthzonkGuOMb7WQit84',
    appId: '1:63043475709:web:9c8fbfc3778d191ad40694',
    messagingSenderId: '63043475709',
    projectId: 'bookapp-5fcb9',
    authDomain: 'bookapp-5fcb9.firebaseapp.com',
    storageBucket: 'bookapp-5fcb9.appspot.com',
    measurementId: 'G-JN95BSYSYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB33lk4_v5PqK7zvNXYgDjByq8oZU2Ejj0',
    appId: '1:63043475709:android:83ca502e1b223e59d40694',
    messagingSenderId: '63043475709',
    projectId: 'bookapp-5fcb9',
    storageBucket: 'bookapp-5fcb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5spLAlSmXB46ETMijam6wag4mLKmpEoQ',
    appId: '1:63043475709:ios:4e37bf47f3cf50e6d40694',
    messagingSenderId: '63043475709',
    projectId: 'bookapp-5fcb9',
    storageBucket: 'bookapp-5fcb9.appspot.com',
    iosBundleId: 'com.example.loginSignupDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5spLAlSmXB46ETMijam6wag4mLKmpEoQ',
    appId: '1:63043475709:ios:4e37bf47f3cf50e6d40694',
    messagingSenderId: '63043475709',
    projectId: 'bookapp-5fcb9',
    storageBucket: 'bookapp-5fcb9.appspot.com',
    iosBundleId: 'com.example.loginSignupDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLqLkXpZwDglQTmthzonkGuOMb7WQit84',
    appId: '1:63043475709:web:c573a3fbd4856701d40694',
    messagingSenderId: '63043475709',
    projectId: 'bookapp-5fcb9',
    authDomain: 'bookapp-5fcb9.firebaseapp.com',
    storageBucket: 'bookapp-5fcb9.appspot.com',
    measurementId: 'G-ZVL951MCD1',
  );
}
